# menu:
#   Блог: blog/
#   Фотографии: albums/
#   Поездки: travel/
#   Статьи: learn/
#   Обо мне: about/
#   In English: http://morning.photos/

#rss: /feed/

#excerpt_link: Читать дальше…

twitter: sapegin
